/*
==========================================================
 Project: E-Commerce SQL Data Analysis
 File: 06_Advanced_Business_Analysis.sql
 Author: Harshad
 Description:
 Advanced SQL queries for business analysis and insights.
==========================================================
*/

USE EcommerceDB;

-- ======================================================
-- SECTION 1 : SALES PERFORMANCE
-- ======================================================

-- 1. Total Revenue
SELECT
    ROUND(SUM(TotalPrice),2) AS Total_Revenue
FROM EcommerceSales;

-- 2. Total Orders
SELECT
    COUNT(OrderID) AS Total_Orders
FROM EcommerceSales;

-- 3. Average Order Value
SELECT
    ROUND(AVG(TotalPrice),2) AS Average_Order_Value
FROM EcommerceSales;

-- 4. Total Quantity Sold
SELECT
    SUM(Quantity) AS Total_Items_Sold
FROM EcommerceSales;

-- 5. Maximum Order Value
SELECT
    MAX(TotalPrice) AS Highest_Order_Value
FROM EcommerceSales;

-- 6. Minimum Order Value
SELECT
    MIN(TotalPrice) AS Lowest_Order_Value
FROM EcommerceSales;

-- ======================================================
-- SECTION 2 : PRODUCT ANALYSIS
-- ======================================================

-- 7. Revenue by Product
SELECT
    Product,
    ROUND(SUM(TotalPrice),2) AS Revenue
FROM EcommerceSales
GROUP BY Product
ORDER BY Revenue DESC;

-- 8. Quantity Sold by Product
SELECT
    Product,
    SUM(Quantity) AS Quantity_Sold
FROM EcommerceSales
GROUP BY Product
ORDER BY Quantity_Sold DESC;

-- 9. Top 5 Products by Revenue
SELECT
    Product,
    ROUND(SUM(TotalPrice),2) AS Revenue
FROM EcommerceSales
GROUP BY Product
ORDER BY Revenue DESC
LIMIT 5;

-- 10. Bottom 5 Products by Revenue
SELECT
    Product,
    ROUND(SUM(TotalPrice),2) AS Revenue
FROM EcommerceSales
GROUP BY Product
ORDER BY Revenue ASC
LIMIT 5;

-- 11. Average Selling Price of Each Product
SELECT
    Product,
    ROUND(AVG(UnitPrice),2) AS Average_Price
FROM EcommerceSales
GROUP BY Product
ORDER BY Average_Price DESC;

-- ======================================================
-- SECTION 3 : CUSTOMER ANALYSIS
-- ======================================================

-- 12. Top 10 Customers by Spending
SELECT
    CustomerID,
    ROUND(SUM(TotalPrice),2) AS Total_Spending
FROM EcommerceSales
GROUP BY CustomerID
ORDER BY Total_Spending DESC
LIMIT 10;

-- 13. Customer Purchase Frequency
SELECT
    CustomerID,
    COUNT(OrderID) AS Orders_Placed
FROM EcommerceSales
GROUP BY CustomerID
ORDER BY Orders_Placed DESC;

-- 14. Average Spending Per Customer
SELECT
    ROUND(AVG(Customer_Total),2) AS Average_Customer_Spending
FROM
(
    SELECT
        CustomerID,
        SUM(TotalPrice) AS Customer_Total
    FROM EcommerceSales
    GROUP BY CustomerID
) AS CustomerSummary;

-- ======================================================
-- SECTION 4 : ORDER STATUS ANALYSIS
-- ======================================================

-- 15. Orders by Status
SELECT
    OrderStatus,
    COUNT(*) AS Total_Orders
FROM EcommerceSales
GROUP BY OrderStatus;

-- 16. Revenue by Order Status
SELECT
    OrderStatus,
    ROUND(SUM(TotalPrice),2) AS Revenue
FROM EcommerceSales
GROUP BY OrderStatus;

-- 17. Cancellation Percentage
SELECT
ROUND(
(
SUM(CASE
WHEN OrderStatus='Cancelled'
THEN 1
ELSE 0
END)
/
COUNT(*)
)*100,2) AS Cancellation_Percentage
FROM EcommerceSales;

-- 18. Return Percentage
SELECT
ROUND(
(
SUM(CASE
WHEN OrderStatus='Returned'
THEN 1
ELSE 0
END)
/
COUNT(*)
)*100,2) AS Return_Percentage
FROM EcommerceSales;

-- ======================================================
-- SECTION 5 : PAYMENT METHOD ANALYSIS
-- ======================================================

-- 19. Revenue by Payment Method
SELECT
    PaymentMethod,
    ROUND(SUM(TotalPrice),2) AS Revenue
FROM EcommerceSales
GROUP BY PaymentMethod
ORDER BY Revenue DESC;

-- 20. Orders by Payment Method
SELECT
    PaymentMethod,
    COUNT(*) AS Orders
FROM EcommerceSales
GROUP BY PaymentMethod
ORDER BY Orders DESC;

-- 21. Average Order Value by Payment Method
SELECT
    PaymentMethod,
    ROUND(AVG(TotalPrice),2) AS Average_Order_Value
FROM EcommerceSales
GROUP BY PaymentMethod
ORDER BY Average_Order_Value DESC;

-- ======================================================
-- SECTION 6 : COUPON ANALYSIS
-- ======================================================

-- 22. Coupon Usage Count
SELECT
    CouponCode,
    COUNT(*) AS Usage_Count
FROM EcommerceSales
GROUP BY CouponCode
ORDER BY Usage_Count DESC;

-- 23. Revenue Generated by Coupon
SELECT
    CouponCode,
    ROUND(SUM(TotalPrice),2) AS Revenue
FROM EcommerceSales
GROUP BY CouponCode
ORDER BY Revenue DESC;

-- ======================================================
-- SECTION 7 : REFERRAL SOURCE ANALYSIS
-- ======================================================

-- 24. Revenue by Referral Source
SELECT
    ReferralSource,
    ROUND(SUM(TotalPrice),2) AS Revenue
FROM EcommerceSales
GROUP BY ReferralSource
ORDER BY Revenue DESC;

-- 25. Orders by Referral Source
SELECT
    ReferralSource,
    COUNT(*) AS Orders
FROM EcommerceSales
GROUP BY ReferralSource
ORDER BY Orders DESC;

-- ======================================================
-- SECTION 8 : MONTHLY SALES ANALYSIS
-- ======================================================

-- 26. Monthly Revenue
SELECT
    MONTHNAME(Date) AS Month,
    ROUND(SUM(TotalPrice),2) AS Revenue
FROM EcommerceSales
GROUP BY MONTH(Date), MONTHNAME(Date)
ORDER BY MONTH(Date);

-- 27. Monthly Orders
SELECT
    MONTHNAME(Date) AS Month,
    COUNT(*) AS Orders
FROM EcommerceSales
GROUP BY MONTH(Date), MONTHNAME(Date)
ORDER BY MONTH(Date);

-- 28. Best Sales Month
SELECT
    MONTHNAME(Date) AS Month,
    ROUND(SUM(TotalPrice),2) AS Revenue
FROM EcommerceSales
GROUP BY MONTH(Date), MONTHNAME(Date)
ORDER BY Revenue DESC
LIMIT 1;

-- ======================================================
-- SECTION 9 : CART ANALYSIS
-- ======================================================

-- 29. Average Items in Cart
SELECT
    ROUND(AVG(ItemsInCart),2) AS Average_Items_Per_Cart
FROM EcommerceSales;

-- 30. Maximum Cart Size
SELECT
    MAX(ItemsInCart) AS Largest_Cart
FROM EcommerceSales;

-- ======================================================
-- SECTION 10 : SHIPPING ANALYSIS
-- ======================================================

-- 31. Orders by Shipping Address
SELECT
    ShippingAddress,
    COUNT(*) AS Orders
FROM EcommerceSales
GROUP BY ShippingAddress
ORDER BY Orders DESC;

-- ======================================================
-- SECTION 11 : REVENUE CONTRIBUTION
-- ======================================================

-- 32. Revenue Contribution Percentage by Product
SELECT
    Product,
    ROUND(
        SUM(TotalPrice) /
        (SELECT SUM(TotalPrice) FROM EcommerceSales)
        *100,
    2) AS Revenue_Percentage
FROM EcommerceSales
GROUP BY Product
ORDER BY Revenue_Percentage DESC;

-- ======================================================
-- SECTION 12 : BONUS ANALYSIS
-- ======================================================

-- 33. Top 10 Highest Value Orders
SELECT
    OrderID,
    CustomerID,
    Product,
    TotalPrice
FROM EcommerceSales
ORDER BY TotalPrice DESC
LIMIT 10;

-- 34. Average Quantity Purchased Per Order
SELECT
    ROUND(AVG(Quantity),2) AS Average_Quantity
FROM EcommerceSales;

-- 35. Distinct Customers
SELECT
    COUNT(DISTINCT CustomerID) AS Unique_Customers
FROM EcommerceSales;

-- 36. Distinct Products
SELECT
    COUNT(DISTINCT Product) AS Unique_Products
FROM EcommerceSales;

-- 37. Distinct Payment Methods
SELECT
    COUNT(DISTINCT PaymentMethod) AS Payment_Methods
FROM EcommerceSales;

-- 38. Distinct Referral Sources
SELECT
    COUNT(DISTINCT ReferralSource) AS Referral_Sources
FROM EcommerceSales;

-- 39. Revenue by Customer
SELECT
    CustomerID,
    ROUND(SUM(TotalPrice),2) AS Revenue
FROM EcommerceSales
GROUP BY CustomerID
ORDER BY Revenue DESC;

-- 40. Final Dashboard Summary
SELECT
    COUNT(OrderID) AS Total_Orders,
    COUNT(DISTINCT CustomerID) AS Total_Customers,
    COUNT(DISTINCT Product) AS Total_Products,
    ROUND(SUM(TotalPrice),2) AS Total_Revenue,
    ROUND(AVG(TotalPrice),2) AS Average_Order_Value,
    SUM(Quantity) AS Total_Items_Sold
FROM EcommerceSales;